### ISSUE TITLE
Adding Q20 and Q30 to nanoplot QC

### ISSUE THREAD

**Issue by tomgutman** [gustaveroussy/long-reads-bulk#1]
In Nanoplot Output (XXXNanoStats.txt) we have :

Reads >Q5:	8927310 (99.9%) 72019.5Mb
Reads >Q7:	8919212 (99.9%) 72009.5Mb
Reads >Q10:	8755396 (98.0%) 71070.2Mb
Reads >Q12:	8212589 (91.9%) 67220.1Mb
Reads >Q15:	6873182 (77.0%) 59158.2Mb

**It would be good to have the same data for Q20 and Q20**

Unfortunately this feature is still in developement (cf nanoplot issues below), so it will be a **feature to add in pipeline V2**

[Q10 to Q30 quality score thresholds not available in latest NanoPlot version
](https://github.com/wdecoster/NanoPlot/issues/371)

[Adding Q30 and Q50 to summary statistics of NanoPlot report](https://github.com/wdecoster/NanoPlot/issues/366)

**Comment by sandratra-rab** [comment]
Hi Tom, 
I've written the first linked issue this week-end indeed! We have included the latest nanomath version to the current NanoPlot singularity image we are using, it works fine and the new thresholds are now Q10, Q15, Q20, Q25, Q30 (we'll update NanoPlot properly if a new version occurs).
